/**
 * Every visible string, in English and Hindi. Kept in one file so a missing
 * translation is obvious, and so the copy can be reviewed for plain language
 * in one sitting. The audience is older readers, many of whom are using a
 * government service online for the first time.
 */
export const STRINGS = {
  en: {
    'app.name': 'SilverPass',
    'app.tagline': 'Passport help, made simple.',
    'app.disclaimer':
      'A demonstration project. Not affiliated with the Passport Seva Kendra or the Ministry of External Affairs, and it does not submit real applications.',
    'a11y.skip': 'Skip to the main content',
    'a11y.textSize': 'Text size',
    'a11y.textNormal': 'Normal text size',
    'a11y.textLarge': 'Large text size',
    'a11y.textLargest': 'Largest text size',
    'a11y.contrast': 'Contrast',
    'a11y.contrastNormal': 'Normal contrast',
    'a11y.contrastHigh': 'High contrast',
    'a11y.language': 'Language',

    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.track': 'Track',
    'nav.dashboard': 'My applications',
    'nav.signIn': 'Sign in',
    'nav.register': 'Create account',
    'nav.signOut': 'Sign out',

    'home.title': 'Apply for your passport without the confusion',
    'home.lede':
      'See what you need, tick it off as you gather it, book a quiet appointment, and check where your passport has got to, all in large and plain language.',
    'home.cta.start': 'Start an application',
    'home.cta.track': 'Track an application',
    'home.step1.title': '1. See what is needed',
    'home.step1.body': 'A plain list of the documents for your situation. No jargon.',
    'home.step2.title': '2. Tick them off',
    'home.step2.body': 'Gather papers at your own pace. We remember where you got to.',
    'home.step3.title': '3. Book a quiet time',
    'home.step3.body': 'Mornings are held back for applicants aged 60 and over.',
    'home.step4.title': '4. Follow the progress',
    'home.step4.body': 'One line telling you what is happening, in words that make sense.',

    'services.title': 'What would you like to do?',
    'services.fee': 'Fee',
    'services.tatkalFee': 'Fast-track fee',
    'services.processing': 'Usually takes',
    'services.days': 'days',
    'services.concession': 'Aged 60 or over? You pay {percent}% less.',
    'services.documents': 'What you will need',
    'services.choose': 'Choose this',

    'auth.signIn': 'Sign in',
    'auth.register': 'Create your account',
    'auth.fullName': 'Your full name',
    'auth.email': 'Email address',
    'auth.emailHint': 'We use this to sign you in.',
    'auth.phone': 'Mobile number',
    'auth.phoneHint': '10 digits, the number you use in India.',
    'auth.password': 'Password',
    'auth.passwordHint': 'At least 8 characters. A short phrase you will remember works well.',
    'auth.dob': 'Your date of birth',
    'auth.dobHint': 'This decides your fee concession and your appointment times.',
    'auth.noAccount': 'No account yet?',
    'auth.haveAccount': 'Already have an account?',
    'auth.signingIn': 'Signing you in...',
    'auth.creating': 'Creating your account...',

    'dash.title': 'My applications',
    'dash.empty': 'You have not started an application yet.',
    'dash.start': 'Start an application',
    'dash.reference': 'Reference number',
    'dash.appointments': 'My appointments',
    'dash.noAppointments': 'No appointment booked yet.',
    'dash.view': 'Open',
    'dash.documentsReady': '{ready} of {total} documents ready',

    'app.status': 'Status',
    'app.checklist': 'Your document checklist',
    'app.checklistHelp': 'Tick each one once you have it in hand.',
    'app.haveIt': 'I have this',
    'app.fee': 'Fee to pay',
    'app.submit': 'Submit this application',
    'app.submitted': 'Submitted',
    'app.cancel': 'Cancel this application',
    'app.cancelConfirm': 'Cancel this application? This cannot be undone.',
    'app.book': 'Book an appointment',
    'app.history': 'What has happened so far',
    'app.applicant': 'Applicant',
    'app.notFound': 'We could not find that application.',

    'new.title': 'Start an application',
    'new.service': 'Which service do you need?',
    'new.scheme': 'How soon do you need it?',
    'new.schemeNormal': 'Normal, the usual wait and the lower fee',
    'new.schemeTatkal': 'Fast-track, quicker but it costs more',
    'new.applicant': 'Who is the passport for?',
    'new.address': 'Current address',
    'new.line1': 'House number and street',
    'new.line2': 'Area or landmark (if any)',
    'new.city': 'City or town',
    'new.state': 'State',
    'new.pincode': 'PIN code',
    'new.assistance': 'Help at the centre',
    'new.assistanceHelp': 'Tell us now and the centre will be ready for you.',
    'new.wheelchair': 'I will need a wheelchair',
    'new.interpreter': 'I will need someone to interpret',
    'new.helperName': 'Name of the person coming with you (if any)',
    'new.helperPhone': 'Their mobile number',
    'new.create': 'Create the application',
    'new.creating': 'Creating...',

    'book.title': 'Book an appointment',
    'book.center': 'Which centre?',
    'book.date': 'Which day?',
    'book.slots': 'Choose a time',
    'book.seatsLeft': '{count} left',
    'book.full': 'Full',
    'book.seniorOnly': 'Held for 60+',
    'book.seniorYours': 'Quiet slot',
    'book.confirm': 'Confirm this appointment',
    'book.booking': 'Booking...',
    'book.stepFree': 'Step-free access',
    'book.noStepFree': 'Has steps at the entrance',
    'book.wheelchairs': 'Wheelchairs available',
    'book.noWheelchairs': 'No wheelchairs on site',
    'book.arrive': 'Please arrive 15 minutes early.',
    'book.cancel': 'Cancel this appointment',
    'book.cancelConfirm': 'Cancel this appointment?',
    'book.noSlots': 'No times are available on that day.',

    'track.title': 'Track an application',
    'track.lede': 'Enter the reference number from your application. You do not need to sign in.',
    'track.reference': 'Reference number',
    'track.referenceHint': 'It looks like SP-ABCD1234.',
    'track.check': 'Check',
    'track.checking': 'Checking...',
    'track.submittedOn': 'Submitted on',
    'track.expected': 'Usually finished within',
    'track.daysSince': 'Days since you applied',

    'common.loading': 'Loading...',
    'common.back': 'Go back',
    'common.required': 'required',
    'common.optional': 'optional',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.somethingWrong': 'Something went wrong. Please try again.',
    'common.fixErrors': 'Please check the details below.',
    'common.notFoundTitle': 'That page does not exist',
    'common.notFoundBody': 'The link may be out of date. Try starting from the home page.',
    'common.goHome': 'Go to the home page',
    'common.signedOut': 'You have been signed out.',
    'common.rupees': '₹{amount}',
  },

  hi: {
    'app.name': 'सिल्वरपास',
    'app.tagline': 'पासपोर्ट सहायता, आसान भाषा में।',
    'app.disclaimer':
      'यह एक प्रदर्शन परियोजना है। इसका पासपोर्ट सेवा केंद्र या विदेश मंत्रालय से कोई संबंध नहीं है, और यह वास्तविक आवेदन जमा नहीं करती।',
    'a11y.skip': 'मुख्य सामग्री पर जाएँ',
    'a11y.textSize': 'अक्षर का आकार',
    'a11y.textNormal': 'सामान्य आकार',
    'a11y.textLarge': 'बड़ा आकार',
    'a11y.textLargest': 'सबसे बड़ा आकार',
    'a11y.contrast': 'रंग स्पष्टता',
    'a11y.contrastNormal': 'सामान्य',
    'a11y.contrastHigh': 'अधिक स्पष्ट',
    'a11y.language': 'भाषा',

    'nav.home': 'मुख्य पृष्ठ',
    'nav.services': 'सेवाएँ',
    'nav.track': 'स्थिति देखें',
    'nav.dashboard': 'मेरे आवेदन',
    'nav.signIn': 'साइन इन',
    'nav.register': 'खाता बनाएँ',
    'nav.signOut': 'साइन आउट',

    'home.title': 'बिना उलझन के पासपोर्ट के लिए आवेदन करें',
    'home.lede':
      'देखें कि क्या चाहिए, इकट्ठा करते जाएँ, शांत समय पर अपॉइंटमेंट लें, और पासपोर्ट कहाँ पहुँचा है यह जानें - बड़े अक्षरों और सरल भाषा में।',
    'home.cta.start': 'आवेदन शुरू करें',
    'home.cta.track': 'स्थिति देखें',
    'home.step1.title': '१. जानें क्या चाहिए',
    'home.step1.body': 'आपकी स्थिति के लिए दस्तावेज़ों की सरल सूची।',
    'home.step2.title': '२. एक-एक करके जमा करें',
    'home.step2.body': 'अपनी गति से इकट्ठा करें। हम याद रखेंगे।',
    'home.step3.title': '३. शांत समय चुनें',
    'home.step3.body': 'सुबह के समय ६० वर्ष से ऊपर के आवेदकों के लिए सुरक्षित हैं।',
    'home.step4.title': '४. प्रगति देखें',
    'home.step4.body': 'सरल शब्दों में एक पंक्ति, जो बताए क्या हो रहा है।',

    'services.title': 'आप क्या करना चाहते हैं?',
    'services.fee': 'शुल्क',
    'services.tatkalFee': 'तत्काल शुल्क',
    'services.processing': 'सामान्यतः लगते हैं',
    'services.days': 'दिन',
    'services.concession': '६० वर्ष या अधिक? आपको {percent}% कम देना होगा।',
    'services.documents': 'क्या-क्या चाहिए',
    'services.choose': 'यह चुनें',

    'auth.signIn': 'साइन इन करें',
    'auth.register': 'अपना खाता बनाएँ',
    'auth.fullName': 'आपका पूरा नाम',
    'auth.email': 'ईमेल पता',
    'auth.emailHint': 'इसी से आप साइन इन करेंगे।',
    'auth.phone': 'मोबाइल नंबर',
    'auth.phoneHint': '१० अंक, भारत का नंबर।',
    'auth.password': 'पासवर्ड',
    'auth.passwordHint': 'कम से कम ८ अक्षर। याद रहने वाला छोटा वाक्य अच्छा रहता है।',
    'auth.dob': 'जन्म तिथि',
    'auth.dobHint': 'इससे आपकी छूट और अपॉइंटमेंट का समय तय होता है।',
    'auth.noAccount': 'अभी खाता नहीं है?',
    'auth.haveAccount': 'पहले से खाता है?',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.creating': 'खाता बन रहा है...',

    'dash.title': 'मेरे आवेदन',
    'dash.empty': 'आपने अभी कोई आवेदन शुरू नहीं किया है।',
    'dash.start': 'आवेदन शुरू करें',
    'dash.reference': 'संदर्भ संख्या',
    'dash.appointments': 'मेरी अपॉइंटमेंट',
    'dash.noAppointments': 'अभी कोई अपॉइंटमेंट नहीं ली गई।',
    'dash.view': 'खोलें',
    'dash.documentsReady': '{total} में से {ready} दस्तावेज़ तैयार',

    'app.status': 'स्थिति',
    'app.checklist': 'आपके दस्तावेज़ों की सूची',
    'app.checklistHelp': 'जो मिल जाए उस पर निशान लगाएँ।',
    'app.haveIt': 'यह मेरे पास है',
    'app.fee': 'देय शुल्क',
    'app.submit': 'आवेदन जमा करें',
    'app.submitted': 'जमा हो गया',
    'app.cancel': 'आवेदन रद्द करें',
    'app.cancelConfirm': 'आवेदन रद्द करें? यह वापस नहीं होगा।',
    'app.book': 'अपॉइंटमेंट लें',
    'app.history': 'अब तक क्या हुआ',
    'app.applicant': 'आवेदक',
    'app.notFound': 'यह आवेदन नहीं मिला।',

    'new.title': 'आवेदन शुरू करें',
    'new.service': 'आपको कौन सी सेवा चाहिए?',
    'new.scheme': 'कितनी जल्दी चाहिए?',
    'new.schemeNormal': 'सामान्य - सामान्य समय, कम शुल्क',
    'new.schemeTatkal': 'तत्काल - जल्दी, पर अधिक शुल्क',
    'new.applicant': 'पासपोर्ट किसके लिए है?',
    'new.address': 'वर्तमान पता',
    'new.line1': 'मकान संख्या और गली',
    'new.line2': 'क्षेत्र या पहचान चिह्न (यदि हो)',
    'new.city': 'शहर या कस्बा',
    'new.state': 'राज्य',
    'new.pincode': 'पिन कोड',
    'new.assistance': 'केंद्र पर सहायता',
    'new.assistanceHelp': 'अभी बता दें, केंद्र तैयार रहेगा।',
    'new.wheelchair': 'मुझे व्हीलचेयर चाहिए',
    'new.interpreter': 'मुझे दुभाषिए की आवश्यकता है',
    'new.helperName': 'साथ आने वाले व्यक्ति का नाम (यदि हो)',
    'new.helperPhone': 'उनका मोबाइल नंबर',
    'new.create': 'आवेदन बनाएँ',
    'new.creating': 'बन रहा है...',

    'book.title': 'अपॉइंटमेंट लें',
    'book.center': 'कौन सा केंद्र?',
    'book.date': 'कौन सा दिन?',
    'book.slots': 'समय चुनें',
    'book.seatsLeft': '{count} शेष',
    'book.full': 'भरा हुआ',
    'book.seniorOnly': '६०+ के लिए',
    'book.seniorYours': 'शांत समय',
    'book.confirm': 'अपॉइंटमेंट पक्की करें',
    'book.booking': 'बुक हो रही है...',
    'book.stepFree': 'सीढ़ी रहित प्रवेश',
    'book.noStepFree': 'प्रवेश पर सीढ़ियाँ हैं',
    'book.wheelchairs': 'व्हीलचेयर उपलब्ध',
    'book.noWheelchairs': 'व्हीलचेयर उपलब्ध नहीं',
    'book.arrive': 'कृपया १५ मिनट पहले पहुँचें।',
    'book.cancel': 'अपॉइंटमेंट रद्द करें',
    'book.cancelConfirm': 'अपॉइंटमेंट रद्द करें?',
    'book.noSlots': 'उस दिन कोई समय उपलब्ध नहीं है।',

    'track.title': 'आवेदन की स्थिति देखें',
    'track.lede': 'अपनी संदर्भ संख्या डालें। साइन इन करने की आवश्यकता नहीं।',
    'track.reference': 'संदर्भ संख्या',
    'track.referenceHint': 'यह SP-ABCD1234 जैसी दिखती है।',
    'track.check': 'देखें',
    'track.checking': 'देख रहे हैं...',
    'track.submittedOn': 'जमा करने की तिथि',
    'track.expected': 'सामान्यतः पूरा होता है',
    'track.daysSince': 'आवेदन को हुए दिन',

    'common.loading': 'लोड हो रहा है...',
    'common.back': 'वापस जाएँ',
    'common.required': 'आवश्यक',
    'common.optional': 'वैकल्पिक',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.somethingWrong': 'कुछ गड़बड़ हुई। कृपया फिर से कोशिश करें।',
    'common.fixErrors': 'कृपया नीचे दी गई जानकारी जाँचें।',
    'common.notFoundTitle': 'यह पृष्ठ मौजूद नहीं है',
    'common.notFoundBody': 'लिंक पुराना हो सकता है। मुख्य पृष्ठ से शुरू करें।',
    'common.goHome': 'मुख्य पृष्ठ पर जाएँ',
    'common.signedOut': 'आप साइन आउट हो गए हैं।',
    'common.rupees': '₹{amount}',
  },
};

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
];
